RISK_MODEL_VERSION = "rules-v1"

LOW_THRESHOLD = 30
HIGH_THRESHOLD = 70

DECISION_LOW = "ALLOW"
DECISION_MEDIUM = "REVIEW"
DECISION_HIGH = "BLOCK"

RISK_LEVEL_LOW = "LOW"
RISK_LEVEL_MEDIUM = "MEDIUM"
RISK_LEVEL_HIGH = "HIGH"

SEVERITY_INFO = "INFO"
SEVERITY_WARNING = "WARNING"
SEVERITY_CRITICAL = "CRITICAL"

RULE_SEVERITY_INFO = "INFO"
RULE_SEVERITY_WARNING = "WARNING"
RULE_SEVERITY_HIGH = "HIGH"
RULE_SEVERITY_CRITICAL = "CRITICAL"

AMOUNT_THRESHOLD_LOW = 25000
AMOUNT_THRESHOLD_MEDIUM = 75000

UNUSUAL_AMOUNT_MULTIPLIER = 5.0

NEW_ACCOUNT_DAYS = 30

HIGH_VELOCITY_THRESHOLD = 6
VELOCITY_ELEVATED_THRESHOLD = 3

FAILED_ATTEMPTS_HIGH = 4
FAILED_ATTEMPTS_ELEVATED = 2

MERCHANT_RISK_HIGH = 61
MERCHANT_RISK_MODERATE = 31

WEIGHT_UNUSUAL_AMOUNT = 25
WEIGHT_HIGH_AMOUNT = 20
WEIGHT_NEW_DEVICE = 15
WEIGHT_LOCATION_CHANGE = 12
WEIGHT_HIGH_VELOCITY = 15
WEIGHT_FAILED_ATTEMPTS = 20
WEIGHT_MERCHANT_RISK = 18
WEIGHT_NEW_ACCOUNT = 10

MAX_SCORE = 100
MIN_SCORE = 0
